// Create view V_ITEM_DETAIL_ROOT // 

create or replace view BUILD_SIM_BOM.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT(
	ITEM_ID,
	ITEM_CLASS_NM,
	ITEM_DSC,
	DELETE_IND
) as
SELECT
  ITEM_ID,
  ITEM_CLASS_NM,
  ITEM_DSC,
  DELETE_IND
FROM
  BUILD_SIM_BOM.BMATHUB_BASE.T_ITEM_DETAIL_ROOT
WHERE
  DELETE_IND = 'FALSE';
