// Create View V_COMPRESS_BOM_CORE //

create or replace view BUILD_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE(
	ITEM,
	ITEM_CLASS_NM,
	ANCHOR_ITEM_ID,
	BOM_NUM,
	LOC
) as
SELECT 
  bc.ITEM,
  bc.ITEM_CLASS_NM,
  cbcv.INPUT_ITEM_ID AS ANCHOR_ITEM_ID,
  bc.BOM_NUM,
  bc.LOC
FROM (
SELECT
  cbc.INPUT_ITEM_ID AS ITEM,
  cbc.ITEM_CLASS_NM,
  ob.INPUT_ITEM_ID AS OUTPUT_ITEM_ID,
  BOM_NUM,
  cbc.LOC
FROM
  BUILD_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE cbc
  INNER JOIN BUILD_SIM_BOM.BMATHUB_XFRM.V_ORIG_BOM ob
  ON cbc.INPUT_ITEM_ID = ob.OUTPUT_ITEM_ID
  WHERE cbc.ITEM_CLASS_NM = 'IC') AS bc
INNER JOIN BUILD_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE cbcv
  ON bc.OUTPUT_ITEM_ID = cbcv.OUTPUT_ITEM_ID;