// Create a View V_SIM_BOM //

create or replace view BUILD_SIM_BOM.BMATHUB_ANALYSIS.V_SIM_BOM(
	ITEM,
	ANCHOR_ITEM_ID,
	BOM_NUM,
	LOC,
	DESCRIP
) as
SELECT 
  sb.ITEM,
  ANCHOR_ITEM_ID,
  sb.BOM_NUM,
  sb.LOC,
  idr.ITEM_DSC AS DESCRIP
FROM
  BUILD_SIM_BOM.BMATHUB_XFRM.V_COMPRESS_BOM_CORE sb 
  INNER JOIN BUILD_SIM_BOM.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT idr ON sb.ITEM = idr.ITEM_ID;
