// Create Table Item Master //

CREATE OR REPLACE TABLE BUILD_SIM_BOM.MASTER_DATA.ITEM(
    ITEM_ID VARCHAR(21) PRIMARY KEY NOT NULL,
    ITEM_CLASS_NM VARCHAR(30), 
    ITEM_DSC VARCHAR(30), 
    DELETE_IND VARCHAR(10)
);
