// Create table T_ITEM_DETAIL_ROOT // 

CREATE OR REPLACE TABLE BUILD_SIM_BOM.BMATHUB_BASE.T_ITEM_DETAIL_ROOT(
    ITEM_ID varchar(21),
    ITEM_CLASS_NM varchar(30),
    ITEM_DSC varchar(30),
    DELETE_IND varchar(10)
);
