// Create Table T_COMPRESS_BOM_CORE

CREATE OR REPLACE TABLE BUILD_SIM_BOM.BMATHUB_BASE.T_COMPRESS_BOM_CORE (
	INPUT_ITEM_ID VARCHAR(21),
	ITEM_CLASS_NM VARCHAR(30),
	OUTPUT_ITEM_ID VARCHAR(21),
	BOM_NUM INTEGER,
	LOC VARCHAR(10)
);
